project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - project-log.qmd
    - wikidata.qmd
    - wikidata-item.ipynb
    - data-models/artist-datamodel.qmd
    - data-models/exhibition-datamodel.qmd
    - ai-use.qmd

title: "BIM Prototype 02"
author:
  - name: "Agustin Carreño"
    orcid: "0009-0009-7574-2731"

website:
  title: "BIM Prototype 02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project-log.qmd
        text: Project Log
      - href: wikidata.qmd
        text: Wikidata
      - href: wikidata-item.ipynb
        text: Item Profile
      - text: "Data Models"
        menu:
          - href: data-models/artist-datamodel.qmd
            text: Artist Data Model
          - href: data-models/exhibition-datamodel.qmd
            text: Exhibition Data Model
      - href: ai-use.qmd
        text: AI Use
    right:
      - icon: github
        href: https://github.com/agustincarrenoo/prototype
        aria-label: GitHub

  repo-url: https://github.com/agustincarrenoo/prototype

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
